seed: 0 # Seed for RNG
timestep: 1.0  # Time in seconds that passes in each step

# Car-related settings
initial_level: "L0"  # Automation level that the simulation starts with
maximum_automation_level: "L4"  # Maximum automation level allowed in the simulation
acc_coefficient: 3.5  # The acceleration with which the car accelerates and decelerates in m/s/s
speed_tolerance: 0  # The maximum speed difference between target speed and the speed the car is driving

# Driver-related settings
allowed_driver_events: ["DISTRACTION", "NDRT"]  # Options are: FATIGUE, DISTRACTION, NDRT, DRIVER_REQUEST
max_occurrences_of_driver_event: [10, 1]  # Number of times a particular driver event can occur
driver_event_probability: [0.99999, 0.0]  # The probability that at least one driver event will occur
initial_fatigue: 0  # Initial fatigue level
initial_distraction: 2  # Initial distraction level
distraction_increase_prob: 0.01  # Probability that a distraction increases at a timestep
distraction_ends_midway_prob: 0.01  # Probability at each timestep that a distraction ends when it is not at max level
distractions_ends_prob: 0.02  # Probability at each timestep that a distraction ends when it is at max level (i.e. 3)
ndrt_ends_prob: 0.001  # Probability that NDRT ends spontaneously at a timestep
driver_request_cancel_prob: 0.005  # The probability that the driver ends the request at each timestep

# Road-related settings
road_length: 2
road_types:
  city:
    min_length: 1
    max_length: 0.1 * road_length
    speed_limit: 50.0
    max_level: L4
    max_occurrences: 3
  rural_minor:
    min_length: 0.1 * road_length
    max_length: 0.4 * road_length
    speed_limit: 60.0
    max_level: L4
    max_occurrences: 2
  rural_major:
    min_length: 0.1 * road_length
    max_length: 0.4 * road_length
    speed_limit: 80.0
    max_level: L4
    max_occurrences: 2
  highway_link:
    min_length: 0.1
    max_length: 0.5
    speed_limit: 60.0
    max_level: L4
    max_occurrences: 2
  highway:
    min_length: 0.5 * road_length
    max_length: road_length
    speed_limit: 100.0
    max_level: L4
    max_occurrences: 1
allowed_road_types: ["city"]

# Road events settings
static_events:
  Turn:
    default_level: "L0"
    default_speed: 30
    min_length: 0.1
    max_length: 0.3
    probability: 0.9
  Roundabout:
    default_level: "L0"
    default_speed: 20
    min_length: 0.1
    max_length: 0.2
    probability: 0.9
  ODD:
    default_level: "L2"
    default_speed: 100
    min_length: 0.1
    max_length: 0.5
    probability: 0.9
allowed_static_events: []  # Options are the static_events that are defined above

dynamic_events:
  Road Works:
    default_level: "L0"
    default_speed: 40
    min_length: 0.1
    max_length: 0.5
    probability: 0.5
    max_occurrences: 1
  Weather:
    default_level: "L2"
    default_speed: 100
    min_length: 2
    max_length: 10
    probability: 0.2
    max_occurrences: 1
  Traffic:
    default_level: "L0"
    default_speed: 25
    min_length: 1
    max_length: 5
    probability: 0.3
    max_occurrences: 1
  Other:
    default_level: "L2"
    default_speed: 100
    min_length: 0.2
    max_length: 0.6
    probability: 0.5
    max_occurrences: 1
allowed_dynamic_events: []
dynamic_event_min_lookahead: 0.05  # Defines minimum distance (in KM) before which dynamic event is detected ahead
dynamic_event_max_lookahead: 1.0  # Defines maximum distance (in KM) before which dynamic event ahead is detected

# Action-related settings
# Available actions are: DN, CANCEL, SSL0, SSL2, SSL3, SSL4, ESL0, ESL2, ESL3, ESL4, CF, CD, PD, CR, ES
available_actions: ['DN', 'SSL4', 'ESL4', 'CD']
instant_actions: true  # When set to true, every action terminates instantly (in the same timestep)

## driver request
ss_resp_prob_dr: 0.999  # Probability that a driver responds when he requested that level
ss_acc_prob_dr: 0.999  # Probability that a driver accepts when he requested that level

## action effects
max_correct_fatigue_time: 10  # The time for which the correct fatigue action runs
cf_success_probability: 0.5  # The probability that correcting fatigue is successful
max_cd_time: 10  # The time for which correct distraction runs
cd_success_probability: 0.1 # 0.95  # The probability that correcting distraction is successful
pd_success_probability: 0.9999  # The probability that preparing the driver is successful
use_parsed_tta_for_actions: false  # If true, the parsed route data is also used as a basis for actions

# Evaluation settings
# Sets the metrics that will be evaluated. The names correspond directly with the classnames of the events, defined in
# several directories in gym_simulator/evaluations
# Current options: CarUnfit, DriverUnfit, QuickTakeover, DoubleSuggestion, RecentSwitch, UnnecessaryES, PendingRequest
evaluation_metrics: [CarUnfit, DriverUnfit, QuickTakeover, DoubleSuggestion, RecentSwitch, UnnecessaryES, PendingRequest]
