# View file containing settings regarding the viewer
# Possible views: ROAD, SPEED, ACTIONS, ACTIONS_SINGLE_LINE, FUTURE_ACTIONS, WOO, STATIC_EVENTS, DYNAMIC_EVENTS, TTAF, TTAU,
#                 DRIVER_EVENTS, DRIVER_STATE, TTDU, TTDF, EVALUATION, DETAILED_EVALUATION, TIME_DRIVEN
views: ["ROAD", "SPEED", "ACTIONS", "ACTIONS_SINGLE_LINE", "FUTURE_ACTIONS", "WOO", "STATIC_EVENTS", "DYNAMIC_EVENTS",
        "TTAF", "TTAU", "DRIVER_STATE", "TTDU", "TTDF", "EVALUATION", "DETAILED_EVALUATION"]
fit_screen: false  # If true, the plots in the GUI fit the screen (and are not scrollable)
render_intermediate: false  # If true, intermediate steps will be rendered, showing live simulation
render_interval: 10  # If render_intermediate is true, every <render_interval> timesteps are shown
start_from: 5  # Start rendering live from a certain position. Only applicable when render_intermediate is true
show_optimistic_lines: false  # If true, also shows optimistic max levels and corresponding TTAF/U
show_pessimistic_lines: false  # If true, also shows pessimistic max levels and corresponding TTAF/U
show_real_ttafu: true  # If true, also shows a line for the actual TTAF/U (calculated in retrospect)
random_start_in_woo: false  # If true, an action will start at a random time within its window of opportunity
partial_render: false  # If true, only part of the route will be rendered, from start_position to end_position as defined below
start_position: 10  # Position to start displaying the route from
end_position: 20  # Position to end displaying the route
